# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: "2"
services:
  namenode:
    image: ubcse587/hadoop-namenode:3.4.1-1
    platform: linux/amd64
    hostname: namenode
    command: [ "/opt/hadoop/namenode.sh" ]
    volumes:
      - namenode:/hadoop/dfs/name
    ports:
      - 9870:9870
      - 8020:8020
    env_file:
      - ./config

  datanode1:
    image: ubcse587/hadoop-datanode:3.4.1-1
    platform: linux/amd64
    hostname: datanode1
    command: [ "hdfs", "datanode" ]
    ports:
      - 50010:50010
      - 50020:50020
      - 50075:50075
      - 9866:9866
    volumes:
      - datanode1:/hadoop/dfs/data
    env_file:
      - ./config

  resourcemanager:
    image: ubcse587/hadoop:3.4.1-1
    platform: linux/amd64
    hostname: resourcemanager
    command: [ "yarn", "resourcemanager" ]
    ports:
      - 8088:8088
    env_file:
      - ./config
    volumes:
      - ./test.sh:/opt/test.sh
  nodemanager:
    hostname: nodemanager
    platform: linux/amd64
    image: ubcse587/hadoop:3.4.1-1
    command: [ "yarn", "nodemanager" ]
    ports:
      - 8042:8042
    env_file:
      - ./config

volumes:
  namenode:
  datanode1:


